version: '3.8'
services:
  users:
    container_name: msusers
    build: ./user
    volumes:
      - ./users/code:/usr/src/app
    networks:
      - msveterinarian
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msveterinarian
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  msveterinarian:
    driver: bridge