version: '3.8'
services:
  friends:
    container_name: msfriends
    build: ./friends
    volumes:
      - ./friends/code:/usr/src/app
    networks:
      - msuvcnl
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msuvcnl
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  msuvcnl:
    driver: bridge